version: '3'

services:
  redis:
    container_name: redis
    hostname: redis
    restart: always
    build:
      context: /redis
      dockerfile: Dockerfile
    image: redis_on_deb/latest
    volumes:
      - ./redis/redis_conf:/usr/local/etc/redis/
      - ./redis/redis_acl:/etc/redis/
      - ./redis/crt:/etc/redis/tls/
      - redisdata:/var/lib/redis/

  golang1:
    container_name: golang
    hostname: golang
    restart: always
    build:
      context: /app
      dockerfile: Dockerfile
    image: backend_golang_at/latest
    volumes:
      - ./app/backend/cert:/backend/cert
    depends_on:
      - redis

  nginx:
    container_name: nginx
    hostname: nginx
    restart: always
    build:
      context: /nginx
      dockerfile: Dockerfile
    image: nginx_on_deb/latest
    ports:
      - "8089:8089"
    depends_on:
      - golang1

volumes:
  redisdata: null